CREATE TABLE category
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN,
    name               VARCHAR(255),
    is_active          BOOLEAN,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE news
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN,
    title              VARCHAR(255),
    content            TEXT,
    status             VARCHAR(255),
    category_id        BIGINT,
    CONSTRAINT pk_news PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT,
    last_modified_by   BIGINT,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    deleted            BOOLEAN,
    username           VARCHAR(255),
    email              VARCHAR(255),
    full_name          VARCHAR(255),
    password           VARCHAR(255),
    is_active          BOOLEAN,
    role               VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE news
    ADD CONSTRAINT FK_NEWS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);